-- mod-tcg-vendors: redemption code tracking table
-- Apply to: characters database
--
-- Each row represents one generated redemption code.
-- Codes are generated by tools/generate_codes.py, which outputs
-- ready-to-run INSERT statements for this table.
--
-- reward_group  : must exactly match a key in the REWARD_GROUPS map
--                 in mod_tcg_vendors.cpp.
-- redeemed      : set to 1 by the C++ module the moment a code is used.
-- account_id    : populated on redemption; NULL while the code is unused.
-- character_guid: populated on redemption; NULL while the code is unused.
-- redeemed_date : populated on redemption; NULL while the code is unused.

CREATE TABLE IF NOT EXISTS `account_tcg_codes` (
    `code`           VARCHAR(19)         NOT NULL
                                         COMMENT 'Redemption code in XXXX-XXXX-XXXX-XXXX format',
    `reward_group`   VARCHAR(64)         NOT NULL
                                         COMMENT 'Reward group key — must match REWARD_GROUPS in mod_tcg_vendors.cpp',
    `redeemed`       TINYINT(1)          NOT NULL DEFAULT 0
                                         COMMENT '0 = available, 1 = already used',
    `account_id`     INT UNSIGNED            NULL DEFAULT NULL
                                         COMMENT 'Account that redeemed this code',
    `character_guid` INT UNSIGNED            NULL DEFAULT NULL
                                         COMMENT 'Character that received the reward',
    `redeemed_date`  TIMESTAMP               NULL DEFAULT NULL
                                         COMMENT 'UTC timestamp of redemption',
    PRIMARY KEY (`code`),
    KEY `idx_reward_group` (`reward_group`),
    KEY `idx_account_id`   (`account_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='Stores pre-generated TCG / Blizzcon promotional redemption codes (mod-tcg-vendors)';
